# Generated by Django 3.0.7 on 2020-07-02 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='items/images/')),
                ('description', models.TextField(blank=True)),
                ('original_cost', models.FloatField()),
                ('revised_cost', models.FloatField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('booked', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('childrenboy', 'Children Boys'), ('childrengirl', 'Children Girls')], max_length=20)),
                ('subcategory', models.CharField(choices=[('saree', 'Saree'), ('kurtis', 'Kurtis'), ('pant', 'Pant'), ('shirt', 'Shirt'), ('top', 'Top'), ('chudidhar', 'Chididhar'), ('other', 'Other')], max_length=20)),
                ('material_type', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('wool', 'Wool'), ('leather', 'Leather'), ('jeans', 'Jeans'), ('other', 'Other')], max_length=20)),
                ('newly_arrived', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
