# Generated by Django 3.0.7 on 2020-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200629_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='newly_arrived',
            field=models.BooleanField(default=0),
        ),
    ]
