# Generated by Django 3.0.7 on 2020-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200630_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material_type',
            field=models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('wool', 'Wool'), ('leather', 'Leather'), ('jeans', 'Jeans'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.CharField(choices=[('saree', 'Saree'), ('kurtis', 'Kurtis'), ('pant', 'Pant'), ('shirt', 'Shirt'), ('top', 'Top'), ('chudidhar', 'Chididhar'), ('other', 'Other')], max_length=20),
        ),
    ]
